id: aurn
label: AURN Network
icon_shape: square
static: no
openair_import_function: importUKAQ
min_period: hourly
available_aggregations:
- hourly
- daily
- monthly
- annual
pollutants:
- no2
- pm25
- pm10
monitoring_type: continuous_automatic
provider: AURN
