id: laqn
label: LAQN Network
icon_shape: triangle
static: no
openair_import_function: importKCL
min_period: hourly
available_aggregations:
- hourly
- daily
- monthly
- annual
pollutants:
- no2
- pm25
- pm10
monitoring_type: continuous_automatic
provider: King's College London
