colours:
  - "#75B3F0"
  - "#63D2E9"
  - "#67E4A6"
  - "#6CF20D"
  - "#F9B11F"
  - "#D92626"
  - "#A32929"
  - "#ffffff"
thresholds:
  - 0
  - 10
  - 20
  - 30
  - 40
  - 60
  - 100
  - .Inf
labels:
  - "< 10"
  - "10-20"
  - "20-30"
  - "30-40"
  - "40-60"
  - "60-100"
  - "> 100"
  - "No data"
title: "NO2, µg/m³"
shape: circle