name: gla_pm25
title: PM<sub>2.5</sub>, µg/m³
pollutant: PM2.5
shape: square
thresholds:
  - 0
  - 5
  - 7.5
  - 10
  - 12.5
  - 15
  - 20
  - 25
  - .Inf
colours:
  - "darkblue"
  - "blue"
  - "lightgreen"
  - "yellow"
  - "orange"
  - "darkorange"
  - "red"
  - "darkred"
  - "white"
labels:
  - "< 5: WHO guideline"
  - "5-7.5"
  - "7.5-10: < GLA/WHO Int 1"
  - "10-12.5"
  - "12.5-15: < WHO Int 2"
  - "15-20: < UK"
  - "20-25: < WHO Int 2"
  - "> 25"
  - "Insufficient data"
